# Change these first
owner: su2umaru # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: su2umarathon
    url: https://su2umarathon.netlify.app/

status-website:
  baseUrl: /repo
  name: Your Status Website
